---
all:
  children:
    tibiacarpet:
      hosts:
        tibiacarpet_local:
          ansible_host: 192.168.100.200
          ansible_ssh_user: "vagrant"
          ansible_ssh_private_key_file: "{{ playbook_dir }}/.vagrant/machines/default/virtualbox/private_key"
