---
- name: Ensure minimal Ansible capability on host.
  hosts: all
  gather_facts: false
  become: true
  tags:
    - setup

  vars:
    ap_python_test_path: "/usr/bin/python"
    ap_python_install_pkg: "python-minimal"

  tasks:
    - name: Ensure the server can run Ansible tasks.
      block:
        - name: Check for Python on the server.
          raw: "test -e {{ ap_python_test_path }}"
          register: python_exists
          changed_when: false
          failed_when: false

        - name: Install Python on the server.
          raw: "apt -y update && apt install -y {{ ap_python_install_pkg }}"
          register: python_installed
          when:
            - "python_exists.rc != 0"
          changed_when:
            - "'0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' not in python_installed.stdout"

# Adapted from https://blog.ssdnodes.com/blog/installing-nextcloud-docker/
- name: Set up containers on host.
  hosts: all
  gather_facts: true
  become: true
  tags:
    - docker

  vars:
    pip_install_packages:
      - name: "docker"
      - name: "docker-compose"

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Set up docker volumes for Nextcloud.
      include_tasks:
        file: "tasks/nextcloud-volumes.yml"
        apply:
          tags:
            - storage
            - volumes
      tags:
        - always

    - name: Set up Nextcloud nginx proxy container.
      include_tasks:
        file: "tasks/nextcloud-nginx.yml"
        apply:
          tags:
            - nginx
            - proxy
      tags:
        - always

    - name: Set up Nextcloud mariadb container.
      include_tasks:
        file: "tasks/nextcloud-mariadb.yml"
        apply:
          tags:
            - database
            - mariadb
      tags:
        - always

    - name: Set up Nextcloud application container.
      include_tasks:
        file: "tasks/nextcloud-app.yml"
        apply:
          tags:
            - app
            - application
      tags:
        - always

    - name: Set up network for Nextcloud containers.
      include_tasks:
        file: "tasks/nextcloud-network.yml"
        apply:
          tags:
            - network
      tags:
        - always
