---
# tasks file for ansible-role-nextcloud-docker

- name: Abort if using insecure values.
  assert:
    that: >
      (nd_postgres_password != 'insecure'
      and nd_redis_host_password != 'insecure'
      and nd_nextcloud_admin_password != 'insecure')
      or nd_allow_insecure_defaults
    fail_msg: "Please change insecure default vars or set 'nd_allow_insecure_defaults: true'"
  when: "nd_domain_name != 'example.local'"

- name: Prepare docker-compose files, and use them to build the app.
  include_tasks:
    file: "nd-docker-compose.yml"
    apply:
      tags:
        - docker
        - docker-compose
        - volumes
  tags:
    - always

- name: Install Nextcloud application.
  include_tasks:
    file: "{{ nd_nextcloud_install_tasks_file }}"
    apply:
      tags:
        - install-nextcloud
        - nextcloud
  tags:
    - always

- name: Run Nextcloud post-configuration commands as needed.
  include_tasks:
    file: "{{ nd_nextcloud_post_install_tasks_file }}"
    apply:
      tags:
        - configure-nextcloud
        - nextcloud
        - post-install
  tags:
    - always
