---
# tasks file for ansible-role-nextcloud-docker

- name: Abort if using insecure values.
  assert:
    that: >
      (nextcloud_config_db_root_password != 'root'
      and nextcloud_config_db_database_password != 'mysql'
      and nextcloud_config_admin_password != 'pass'
      and nextcloud_redis_container_host_password != 'pass')
      or nextcloud_config_allow_insecure_defaults
    fail_msg: "Please change insecure default vars or set 'nextcloud_config_allow_insecure_defaults: true'"
  when: "nextcloud_config_domain != 'example.local'"

- name: Set up docker volumes for Nextcloud.
  include_tasks:
    file: "nextcloud-volumes.yml"
    apply:
      tags:
        - storage
        - volumes
  tags:
    - always

- name: Set up network for Nextcloud containers.
  include_tasks:
    file: "nextcloud-network.yml"
    apply:
      tags:
        - network
  tags:
    - always

- name: Set up Nextcloud nginx proxy container.
  include_tasks:
    file: "nextcloud-nginx.yml"
    apply:
      tags:
        - nginx
        - proxy
  tags:
    - always

- name: Set up Letsencrypt container.
  include_tasks:
    file: "nextcloud-letsencrypt.yml"
    apply:
      tags:
        - letsencrypt
        - ssl
        - tls
  when: nextcloud_letsencrypt_enable
  tags:
    - always

- name: Set up Nextcloud mariadb container.
  include_tasks:
    file: "nextcloud-mariadb.yml"
    apply:
      tags:
        - database
        - mariadb
  tags:
    - always

- name: Set up Nextcloud redis container.
  include_tasks:
    file: "nextcloud-redis.yml"
    apply:
      tags:
        - cache
        - redis
  tags:
    - always

- name: Set up Nextcloud application container.
  include_tasks:
    file: "nextcloud-app.yml"
    apply:
      tags:
        - app
        - application
  tags:
    - always

- name: Complete Nextcloud install from cli.
  include_tasks:
    file: "nextcloud-install.yml"
    apply:
      tags:
        - install
        - nextcloud
  tags:
    - always

- name: Add cron tasks for Nextcloud app.
  include_tasks:
    file: "{{ nextcloud_cron_tasks_include }}"
    apply:
      tags:
        - cron
        - nextcloud
  tags:
    - always
