---
# tasks file for ansible-role-nextcloud-docker

- name: Set up docker volumes for Nextcloud.
  include_tasks:
    file: "nextcloud-volumes.yml"
    apply:
      tags:
        - storage
        - volumes
  tags:
    - always

- name: Set up Nextcloud nginx proxy container.
  include_tasks:
    file: "nextcloud-nginx.yml"
    apply:
      tags:
        - nginx
        - proxy
  tags:
    - always

- name: Set up Nextcloud mariadb container.
  include_tasks:
    file: "nextcloud-mariadb.yml"
    apply:
      tags:
        - database
        - mariadb
  tags:
    - always

- name: Set up Nextcloud application container.
  include_tasks:
    file: "nextcloud-app.yml"
    apply:
      tags:
        - app
        - application
  tags:
    - always

- name: Set up network for Nextcloud containers.
  include_tasks:
    file: "nextcloud-network.yml"
    apply:
      tags:
        - network
  tags:
    - always

- name: Complete Nextcloud install from cli.
  include_tasks:
    file: "install.yml"
    apply:
      tags:
        - install
        - nextcloud
  tags:
    - always
