---
# tasks related to docker-compose for ansible-role-nextcloud-docker.

- name: Create directory for docker-compose files on remote.
  file:
    path: "{{ nd_docker_compose_project_dir }}"
    state: directory
  changed_when: false

- name: Transfer and populate env file for database container.
  template:
    src: "{{ nd_docker_compose_project_src }}/db.env.j2"
    dest: "{{ nd_docker_compose_project_dir }}/db.env"
  changed_when: false
  # The env file may contain one or more passwords.
  no_log: true

- name: Transfer dockerfile to remote.
  template:
    src: "{{ nd_docker_compose_project_src }}/docker-compose.yml.j2"
    dest: "{{ nd_docker_compose_project_dir }}/docker-compose.yml"
  changed_when: false
  # The dockerfile may contain one or more passwords.
  no_log: true

- name: Copy Nextcloud dockerfile dependencies to remote.
  copy:
    src: "{{ nd_docker_compose_project_src }}/proxy"
    dest: "{{ nd_docker_compose_project_dir }}"
  changed_when: false

- name: Build and start Nextcloud with docker-compose.
  docker_compose:
    build: false
    project_src: "{{ nd_docker_compose_project_dir }}"
    restarted: true
  changed_when: false
  register: nd_docker_compose_output

- name: Remove docker-compose directory and files on remote.
  file:
    path: "{{ nd_docker_compose_project_dir }}"
    state: absent
  changed_when: false
  when: "nd_docker_compose_remove_project"

- name: Test status of containers.
  include_tasks:
    file: "tasks/nd-docker-status.yml"
  loop: "{{ nd_docker_compose | dict2items }}"
  loop_control:
    loop_var: container
