---
# tasks related to Nextcloud initial config for ansible-role-nextcloud-docker.

- name: Enable Nextcloud apps, and encryption, and run occ commands.
  include_tasks:
    file: "nd-nextcloud-occ.yml"
  loop: "{{ nd_nextcloud_occ_commands }}"
  loop_control:
    loop_var: occ
