---
# Runs occ tasks for Nextcloud.
#
# Notes:
#
# - There are so many possible commands that could be run here that we can't
#   practically check for idempotence.
# - We also can't set and make use of variables from individual commands using
#   register, so commands that need to make use of e.g. rc or stdout should
#   be written directly (as in nd-nextcloud-install.yml).
- name: Run {{ (occ.private is defined) | ternary('private command', occ.command) }} on Nextcloud container.
  shell: "{{ nd_nextcloud_occ_prefix }} php occ {{ occ.command }}"
  changed_when: false
  when: "not ansible_check_mode"
  no_log: "{{ occ.private is defined }}"
