---
# Tasks related to nextcloud-redis container (db cache) for
# ansible-role-nextcloud-docker.

- name: Find out if the Redis container is present and started.
  docker_container_info:
    name: "{{ nextcloud_redis_container_name }}"
  register: nextcloud_redis_container_info

- name: Ensure the Redis container is present and started.
  docker_container:
    # This is probably insufficient: what if the container restarts for any
    # reason in a non-Ansible context?
    #
    # https://nickjanetakis.com/blog/docker-tip-27-setting-a-password-on-redis-without-a-custom-config
    command: >
      --requirepass {{ nextcloud_redis_container_host_password }}
    image: "{{ nextcloud_redis_container_image }}"
    name: "{{ nextcloud_redis_container_name }}"
    networks:
      - name: "{{ nextcloud_network_name }}"
    published_ports: "{{ nextcloud_redis_container_ports }}"
    restart: "{{ nextcloud_redis_container_restart }}"
    state: "{{ nextcloud_redis_container_state }}"
  when: >
    not nextcloud_redis_container_info.exists or
    not nextcloud_redis_container_info.container.State.Running
