---
# Tasks related to nextcloud-mariadb container (db server) for
# ansible-role-nextcloud-docker.

- name: Find out if the Mariadb container is present and started.
  docker_container_info:
    name: "{{ nextcloud_mariadb_container_name }}"
  register: nextcloud_mariadb_container_info

- name: Ensure the Mariadb container is present and started.
  docker_container:
    env: "{{ nextcloud_mariadb_container_env | items2dict }}"
    image: "{{ nextcloud_mariadb_container_image }}"
    name: "{{ nextcloud_mariadb_container_name }}"
    networks:
      - "{{ nextcloud_network_name }}" 
    restart: "{{ nextcloud_mariadb_container_restart }}"
    state: "{{ nextcloud_mariadb_container_state }}"
    volumes: "{{ nextcloud_mariadb_container_volumes }}"
  when: >
    not nextcloud_mariadb_container_info.exists or
    not nextcloud_mariadb_container_info.container.State.Running
