---
# Tasks related to nextcloud-nginx container (proxy) for
# ansible-role-nextcloud-docker.

- name: Find out if the Nginx proxy container is present and started.
  docker_container_info:
    name: "{{ nextcloud_nginx_container_name }}"
  register: nextcloud_nginx_container_info

- name: Ensure the Nginx proxy container is present and started.
  docker_container:
    exposed_ports: "{{ nextcloud_nginx_container_ports }}"
    image: "{{ nextcloud_nginx_container_image }}"
    name: "{{ nextcloud_nginx_container_name }}"
    networks:
      - name: "{{ nextcloud_network_name }}"
    published_ports: "{{ nextcloud_nginx_container_ports }}"
    restart: "{{ nextcloud_nginx_container_restart }}"
    state: "{{ nextcloud_nginx_container_state }}"
    volumes: "{{ nextcloud_nginx_container_volumes }}"
  when: >
    not nextcloud_nginx_container_info.exists or
    not nextcloud_nginx_container_info.container.State.Running
