---
- name: Converge
  hosts: all
  become: true
  become_user: root
  vars:
    nd_use_letsencrypt: false
    nd_docker_compose_remove_project: false
    nd_domain_name: "instance"
    nd_postgres_password: "postgres-password"
    nd_redis_host_password: "redis-host-password"
    nd_nextcloud_admin_password: "nextcloud-admin-password"
    nd_nextcloud_required_volumes:
      - "nextcloud:/var/www/html"
      - "/var/nextcloud/config:/var/www/html/config"
      - "/var/nextcloud/custom_apps:/var/www/html/custom_apps"
      - "/var/nextcloud/data:/var/www/html/data"
      - "/var/nextcloud/themes:/var/www/html/themes"
  roles:
    - role: ansible-role-nextcloud-docker
