---
- name: Converge
  hosts: all
  become: true
  become_user: root
  vars:
    nd_secure_no_log: false
    nd_docker_compose_project_src: "{{ playbook_dir }}/../files/docker-compose"
    nd_docker_compose_remove_project: false
    nd_domain_name: "instance"
    nd_postgres_password: "postgres-password"
    nd_redis_host_password: "redis-host-password"
    nd_nextcloud_admin_password: "nextcloud-admin-password"
    nd_docker_compose:
      app:
        environment:
          - "VIRTUAL_HOST={{ nd_domain_name }}"
          - "LETSENCRYPT_HOST={{ nd_domain_name }}"
          - "LETSENCRYPT_EMAIL=admin@example.local"
          - "POSTGRES_HOST={{ nd_postgres_host }}"
          - "REDIS_HOST={{ nd_redis_host }}"
        networks:
          - "default"
          - "{{ nd_docker_network }}"
        volumes:
          - "{{ nd_docker_volumes.app }}:/var/www/html"
      db:
        environment:
          - "POSTGRES_DB={{ nd_postgres_database }}"
          - "POSTGRES_HOST={{ nd_postgres_host }}"
          - "POSTGRES_PASSWORD={{ nd_postgres_password }}"
          - "POSTGRES_USER={{ nd_postgres_user }}"
        volumes:
          - "{{ nd_docker_volumes.db }}:/var/lib/postgresql/data"
      proxy:
        networks:
          - "{{ nd_docker_network }}"
        volumes:
          - "{{ nd_docker_volumes.proxy.conf }}:/etc/nginx/vhost.d"
          - "{{ nd_docker_volumes.proxy.docroot }}:/usr/share/nginx/html"
          - "/var/run/docker.sock:/tmp/docker.sock:ro"
      redis:
        environment:
          - "REDIS_HOST={{ nd_redis_host }}"
          - "REDIS_HOST_PORT={{ nd_redis_port }}"
          - "REDIS_HOST_PASSWORD={{ nd_redis_host_password }}"
  roles:
    - role: ansible-role-nextcloud-docker
