---
- name: Converge
  hosts: all
  become: true
  become_user: root
  vars:
    nd_docker_compose_remove_project: false
    nd_domain_name: "instance"
    nd_mariadb_root_password: "mysql-root-password"
    nd_mariadb_password: "mysql-password"
    nd_redis_host_password: "redis-host-password"
    nd_nextcloud_admin_password: "nextcloud-admin-password"
  roles:
    - role: ansible-role-nextcloud-docker
