---
# Tasks related to nextcloud-app container (Nextcloud itself).

- name: Ensure the Nextcloud container is present.
  docker_container:
    name: "nextcloud-app"
    image: "nextcloud:latest"
    # networks:
    #  - name: "nextcloud_network"
    volumes:
      - "nextcloud:/var/www/html"
      - "./app/config:/var/www/html/config"
      - "./app/custom_apps:/var/www/html/custom_apps"
      - "./app/data:/var/www/html/data"
      - "./app/themes:/var/www/html/themes"
      - "/etc/localtime:/etc/localtime:ro"
    env:
      VIRTUAL_HOST: "tibiacarpet.local"
    restart: true
    state: started
