---
# Tasks related to nextcloud-app container (Nextcloud itself) for
# ansible-role-nextcloud-docker.

- name: Ensure the Nextcloud app container is present.
  docker_container:
    name: "{{ nextcloud_app_container_name }}"
    image: "{{ nextcloud_app_container_version }}"
    volumes: "{{ nextcloud_app_container_volumes }}"
    env: "{{ nextcloud_app_container_env | items2dict }}"
    restart: "{{ nextcloud_app_container_restart }}"
    state: "{{ nextcloud_app_container_state }}"
