---
# Tasks related to nextcloud-mariadb container (db server) for
# ansible-role-nextcloud-docker.

- name: Ensure the Mariadb container is present.
  docker_container:
    name: "{{ nextcloud_mariadb_container_name }}"
    image: "{{ nextcloud_mariadb_container_image }}"
    volumes: "{{ nextcloud_mariadb_container_volumes }}"
    env: "{{ nextcloud_mariadb_container_env | items2dict }}"
    restart: "{{ nextcloud_mariadb_container_restart }}"
    state: "{{ nextcloud_mariadb_container_state }}"
